name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    name: Run Playwright tests
    container:
      image: mcr.microsoft.com/playwright:v1.41.2-jammy
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: github
          POSTGRES_PASSWORD: password123
          POSTGRES_DB: devertix
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgres://github:password123@postgres:5432/devertix
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1
    - name: Install dependencies
      run: bun install
    - name: Install Playwright Browsers
      run: bunx playwright install --with-deps
    - name: Run migrations
      run: bun run migrate
    - name: Run seeder
      run: bun run seed
    - name: Run Playwright tests
      run: bun run test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
